#include <stdio.h>
#include <stdlib.h>
#include <string.h>


/**
 * @brief Get the File object
 * 
 * @param path relative path to the File
 * @return FILE* if file existed: File, else: Null
 */
FILE* getFile(char* path) {
    FILE* fp = fopen(path, "r");
    if (fp == NULL) {
        printf("Error: Couldnt open file %s", path);
        return NULL;
    }
    return fp;
} 

/**
 * @brief Get the Next Line object
 * 
 * @param fp File with read rights
 * @param MAX_LENGTH Max length of bytes which are read per line
 * @return char* line content with length max_length
 */
char* getNextLine(FILE* fp, const unsigned MAX_LENGTH) {
    char* buffer = malloc(sizeof(char) * MAX_LENGTH);
    if (fgets(buffer, MAX_LENGTH, fp)) {
        return buffer;
    } else {
        return NULL;
    }
}

/**
 * @brief removes blank spaces generated by reading lines by a larger buffer
 * 
 * @param str string which has to be cleaned up
 * @return char* string without unnessesary blank spaces
 */
char* clearString(char* str) {
    return strtok(str, "\n");
}

/**
 * @brief returns the length of a string
 * 
 * @param str string with terminal '\0'
 * @return int length of the string
 */
int getLength(char* str) {
    int i = 0; 
    while (str[i] != '\0') {
        i++;
    }
    return i;
}


int t1_findDoubleChar(char* str) {
    int n = getLength(str);
    for (int i = 0; i < n / 2; i++) {
        for (int j = n / 2; j < n; j++) {
            if (str[i] == str[j]) {
                return str[i] > 96 ? str[i] - 96 : str[i] - 38;
            }
        }
    }
}

int hasCharIn(char* str, char c) {
    int n = getLength(str);
    for (int i = 0; i < n; i++) {
        if (str[i] == c) {
            return 1;
        }
    }
    return 0;
}

int t2_findOnlyChar(char* l1, char* l2, char* l3) {
    int n = getLength(l1);
    for (int i = 0; i < n; i++) {
        if (hasCharIn(l2, l1[i]) && hasCharIn(l3, l1[i])) {
            // printf("%s %s %s has in common: %c\n", l1, l2, l3, l1[i]);
            return l1[i] > 96 ? l1[i] - 96 : l1[i] - 38;
        }
    }
    return 0;
}


int main() {
    FILE* input = getFile("input.txt");
    char* line1 = getNextLine(input, 256);
    char* line2 = getNextLine(input, 256);
    char* line3 = getNextLine(input, 256);
    
    int sum = 0;
    while (line1 != NULL && line2 != NULL && line3 != NULL) {
        
        sum += t2_findOnlyChar(clearString(line1), clearString(line2), clearString(line3));

        free(line1);
        free(line2);
        free(line3);
        line1 = getNextLine(input, 256);
        line2 = getNextLine(input, 256);
        line3 = getNextLine(input, 256);
    } 
    printf("Summe: %d", sum);
    return 1;
}