#include <stdio.h>
#include <stdlib.h>
#include <string.h>


/**
 * @brief Get the File object
 * 
 * @param path relative path to the File
 * @return FILE* if file existed: File, else: Null
 */
FILE* getFile(char* path) {
    FILE* fp = fopen(path, "r");
    if (fp == NULL) {
        printf("Error: Couldnt open file %s", path);
        return NULL;
    }
    return fp;
} 

/**
 * @brief Get the Next Line object
 * 
 * @param fp File with read rights
 * @param MAX_LENGTH Max length of bytes which are read per line
 * @return char* line content with length max_length
 */
char* getNextLine(FILE* fp, const unsigned MAX_LENGTH) {
    char* buffer = malloc(sizeof(char) * MAX_LENGTH);
    if (fgets(buffer, MAX_LENGTH, fp)) {
        return buffer;
    } else {
        return NULL;
    }
}

/**
 * @brief removes blank spaces generated by reading lines by a larger buffer
 * 
 * @param str string which has to be cleaned up
 * @return char* string without unnessesary blank spaces
 */
char* clearString(char* str) {
    return strtok(str, "\n");
}

/**
 * @brief returns the length of a string
 * 
 * @param str string with terminal '\0'
 * @return int length of the string
 */
int getLength(char* str) {
    int i = 0; 
    while (str[i] != '\0') {
        i++;
    }
    return i;
}


int hasCharIn(char* str, char c) {
    int n = getLength(str);
    for (int i = 0; i < n; i++) {
        if (str[i] == c) {
            return 1;
        }
    }
    return 0;
}

int t1_isIn(char* str) {
    char* firstElf = strtok(str, ",");
    char* secondElf = strtok(NULL, ",");

    int fE_fN = atoi(strtok(firstElf, "-"));
    int fE_lN = atoi(strtok(NULL, "-"));

    int sE_fN = atoi(strtok(secondElf, "-"));
    int sE_lN = atoi(strtok(NULL, "-"));

    // printf("%d to %d - %d to %d \n", fE_fN, fE_lN, sE_fN, sE_lN);
    if ((fE_fN >= sE_fN && fE_lN <= sE_lN) || (sE_fN >= fE_fN && sE_lN <= fE_lN)) {
        return 1;
    }
    
    return 0;
}



int t2_isIn(char* str) {
    char* firstElf = strtok(str, ",");
    char* secondElf = strtok(NULL, ",");

    int fE_fN = atoi(strtok(firstElf, "-"));
    int fE_lN = atoi(strtok(NULL, "-"));

    int sE_fN = atoi(strtok(secondElf, "-"));
    int sE_lN = atoi(strtok(NULL, "-"));

    // printf("%d to %d - %d to %d", fE_fN, fE_lN, sE_fN, sE_lN);
    if ((fE_lN >= sE_fN && fE_fN <= sE_fN)
        || (fE_fN >= sE_fN && fE_lN <= sE_lN)
        || (sE_fN >= fE_fN && sE_lN <= fE_lN)
        || (sE_lN <= fE_lN && sE_lN >= fE_fN)
        ) {
        // printf("--> 1\n");
        return 1;
    }
    // printf("--> 0\n");
    return 0;
}

int main() {
    FILE* input = getFile("input.txt");
    char* line = getNextLine(input, 256);
    
    int sum = 0;
    int t2_sum = 0;
    int debug = 0;
    while (line != NULL) {   
        // sum += t1_isIn(clearString(line));
        t2_sum += t2_isIn(clearString(line));

        free(line);
        line = getNextLine(input, 256);
    } 
    printf("Summe: %d \n Summe2: %d", sum, t2_sum);
    return 1;
}